### ISSUE TITLE
PhpAmqpLib PCNTLHeartbeatSender

### ISSUE THREAD

**Issue by basz** [prolic/HumusAmqp#100]
Since [2.12.0](https://github.com/php-amqplib/php-amqplib/milestone/14?closed=1) of PhpAmqpLib an PCNTLHeartbeatSender was introduced. It seems to fix and issue of mine with long running (docker) processes where connections to rabbitMQ are being dropped when no messages are send for a longer period of time.

A quick test revealed to me that simple adding the following to the [connection factory](https://github.com/prolic/HumusAmqp/blob/master/src/Container/ConnectionFactory.php#L128) would enable the PCNTLHeartbeatSender.

```
                try {
                    $sender = new PCNTLHeartbeatSender($connection->getResource());
                    $sender->register();
                } catch (AMQPRuntimeException $exception) {
                    // ignore
                }
```

Now I m using a socket connection and am not sure if other connections would benefit also. Not familiar with those. Especially the lazy ones. So not sure if I could create a PR that adds them to all or only some specific ones. Please advise.

**Comment by prolic** [comment]
Reading through https://github.com/php-amqplib/php-amqplib/pull/815 I think it makes sense to enable this for all connections. I'd say let's put it into the options and make it configurable, whether or not to enable it. By default it should be disabled, as this might be a breaking change for someone.

**Comment by basz** [comment]
Yep ok. I'll add that then today or tomorrow. Thx!

**Comment by prolic** [comment]
resolved via https://github.com/prolic/HumusAmqp/pull/102
