### ISSUE TITLE
Fatal Error due to conflicting constructor signature for AmqpExtension::Envelope

### ISSUE THREAD

**Issue by basz** [prolic/HumusAmqp#18]
When consuming a message a Fatal Error occurs

```
Fatal error: Uncaught TypeError: Argument 1 passed to Humus\Amqp\Driver\AmqpExtension\Envelope::__construct() must be an instance of AMQPBasicProperties, instance of AMQPEnvelope given, called in .../vendor/prolic/humus-amqp/src/Driver/AmqpExtension/Queue.php on line 159 and defined in .../vendor/prolic/humus-amqp/src/Driver/AmqpExtension/Envelope.php:42
```

Which seems logical because of these definitions:
https://github.com/prolic/HumusAmqp/blob/master/src/Driver/AmqpExtension/Queue.php#L158-L159
https://github.com/prolic/HumusAmqp/blob/master/src/Driver/AmqpExtension/Envelope.php#L42

I can 'open' (PHPStorm) `\AMQPEnvelope` but not `\AMQPBasicProperties`.

**Comment by prolic** [comment]
As said in the PR, you have to compile ext-amqp from master.
