### ISSUE TITLE
TypeError when trying to set up consumer on CLI

### ISSUE THREAD

**Issue by jeremymills** [prolic/HumusAmqp#22]
Trying to set up a consumer running from CLI and after setting up my `humus-amqp-config.php` file I get this error when I run any `./vendor/bin/humus-amqp` commands. I can't seem to find any documentation on it

```sh
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Humus\Amqp\Console\ConsoleRunner::run() must be an instance of 
Symfony\Component\Console\Helper\HelperSet, array given, called in [project_dir]/vendor/prolic/humus-amqp/bin/humus-amqp.php on 
line 68 and defined in [project_dir]/vendor/prolic/humus-amqp/src/Console/ConsoleRunner.php:57
```

**Comment by prolic** [comment]
Can you post your humus-amqp-config.php?

**Comment by jeremymills** [comment]
Hey @prolic I figured it out, there is a message that prints out when you don't have the humus-amqp-config.php set up.. just couldn't see any mention of it anywhere in the docs? did I miss it? otherwise it would be nice to have some mention in there.

Thanks for the quick reply, you can close this issue though, cheers.

for anyone else:

My issue was that I didn't have the humus-amqp-config.php file set up properly.. there is  consol promt that gives you an example of how to invoke the container into the helper. The instructions are clear enough I just didn't see the consol output (my bad)
