### ISSUE TITLE
Link to gitter chat in readme does not work

### ISSUE THREAD

**Issue by bartmcleod** [prolic/HumusAmqp#42]
When I click the link to the gitter chat in the readme it leads to a 404.

**Comment by prolic** [comment]
I just tested and it works for me. Did you signed up on gitter?

**Comment by bartmcleod** [comment]
No, I did not sign up...

**Comment by prolic** [comment]
Ok I tested again in private mode with my browser (also not logged in) and the link works!
https://gitter.im/prolic/HumusAmqp

**Comment by bartmcleod** [comment]
I was looking at this link: https://gitter.im/prolic/improoph

**Comment by prolic** [comment]
Fixed with via 32741c1e1b8666ebf56c6ee4584f6772fdf3cb2f. Thanks for the info!
