### ISSUE TITLE
Compatibility with latest ConfigurationTrait

### ISSUE THREAD

**Issue by bartmcleod** [prolic/HumusAmqp#44]
The factories implement RequiresConfig, RequiresMandatoryOptions. These however got new return types since their 2.0 release. The return types used in HumusAmqp are still `array`. The new return type for the methods `dimensions()` and `mandatoryOptions()` is `iterable`

Reproduce by installing the latest `sandrokeil/interop-config`

**Comment by prolic** [comment]
array return type is compatible with iterable, see:

```
interface Foo { public function get(): iterable; }
class Bar { public function get(): array { return []; } }
$bar = new Bar();
var_dump($bar->get());
```

No throwable at all. However you are free to submit a PR to change that.

**Comment by bartmcleod** [comment]
hmz, I got a warning: declaration of dimensions() must be compatible with... etc I think you forgot to write `class Bar implements Foo`. That's why your snippet just works.

**Comment by sandrokeil** [comment]
@bartmcleod There is no error if return type `array` differs from `iterable` see [my tests](https://github.com/sandrokeil/interop-config/blob/master/test/TestAsset/PackageDefaultAndMandatoryOptionsConfiguration.php#L34). What PHP error get you exactly?

**Comment by bartmcleod** [comment]
I'm afraid I cannot reproduce it... I downgraded my version of interop-config to 1.2, because of the error, but even installing 2.1 does not bring the error back. I don't remember which script caused it. Probably setup-fabric command, but that is currently broken in my setup. If I see it again I will report it back to you.

**Comment by prolic** [comment]
Anyway feel free to submit a PR to change this.
