### ISSUE TITLE
Customizable the delivery result when handling exception

### ISSUE THREAD

**Issue by yethee** [prolic/HumusAmqp#49]
Hi!

Currently, the `CallbackConsumer` always sends nack with requeue flag, when catch an exception. But we use DLX in our app, and need to shutdown consumer and send nack without requeue flag when an exception was not suppressed in the callback.

Can we change so that `handleException` method returns the delivery result? Then we would have an extension point - the error callback.

**Comment by prolic** [comment]
Sounds reasonable, are you able to provide a PR?
I found two usages:
1) AbstractConsumer.php:149
2) AbstractConsumer.php:258

**Comment by prolic** [comment]
@yethee can you take care of it?

**Comment by yethee** [comment]
Sorry for delay. I will try to create PR in the coming days.
