### ISSUE TITLE
Consider implementing amqp-interop

### ISSUE THREAD

**Issue by prolic** [prolic/HumusAmqp#50]
https://github.com/queue-interop/amqp-interop

**Comment by prolic** [comment]
This will not be done, because it's not requiring PHP 7, so no strict type, scalar type hinting, etc.

**Comment by makasim** [comment]
@prolic would your decision change if we drop PHP 5 support? It's under discussion now.

**Comment by prolic** [comment]
I could reconsider it, yes.
