### ISSUE TITLE
New major release

### ISSUE THREAD

**Issue by prolic** [prolic/HumusAmqp#89]
What other issue do we need to address?

ping @thomasvargiu @rppgorecki @genhoi @func0der

**Comment by prolic** [comment]
https://github.com/prolic/HumusAmqp/pull/84 will get merged later today

**Comment by prolic** [comment]
@bweston92 @oqq maybe?

There are a few issues in the backlog, if someone wants to work on them, we can put them into this upcoming new major release as well. Especially https://github.com/prolic/HumusAmqp/issues/69, https://github.com/prolic/HumusAmqp/issues/65, https://github.com/prolic/HumusAmqp/issues/64 and https://github.com/prolic/HumusAmqp/issues/70.

**Comment by rppgorecki** [comment]
See #91 - it's draft for (#69 and #64). I can try to implement factory for errors (#70) later this week, but I'm not quite sure if it's really necessary.

**Comment by genhoi** [comment]
I have no issue. Waiting for release)
